{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"사설망 단말에서 웹서버 연결"}]}]}]}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(1a) NAT 뒤에서 리퀘스트를 시작"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(1b) NAT는 기기 IP 주소를 공인 IP 주소로 매핑하고 리퀘스트를 웹 서버로 전달한다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(2) 웹 서버는 데이터 패킷을 NAT의 IP 주소로 응답 전달 한다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(3) NAT는 매핑된 기기의 IP 주소로 그 응답을 전달 한다."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NAT-device-to-server-view-a-web-page"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"사설망-사설망 미디어 연결"}]}]}]}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(1a) NAT 뒤에서 요청을 시작한다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(1b) NAT는 기기의 IP 주소를 공인 IP 주소로 매핑하고 상대 기기로 요청을 전달한다. 이 요청은 수신 기기의 NAT에 전달되고, 이 요청은 NAT 뒤의 기기에서 시작된 요청에 대한 응답이 아니므로 NAT가 그 연결을 차단한다. (NAT는 어느 기기로 요청을 전달해야 하는지 알 수 없으므로)"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NAT-device-to-server-make-a-video-call"}]},{"anchor":"NAT-투과-기술의-이해","level":3,"type":"heading","text":"NAT 투과 기술의 이해"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"STUN Binding"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NAT-traversal-STUN-binding"}]},{"type":"orderedList","start":2,"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Caller TURN allocation"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NAT-traversal-Caller-TURN-allocation"}]},{"type":"orderedList","start":3,"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Caller sends invite"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NAT-traversal-caller-sends-invite"}]},{"type":"orderedList","start":4,"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callee TURN allocation"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NAT-traversal-Callee-TURN-allocation"}]},{"type":"orderedList","start":5,"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callee answer OK"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NAT-traversal-callee-answers-OK"}]},{"type":"orderedList","start":6,"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Exchange candidate IP address"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NAT-traversal-exchange-candidate-IP-addresses"}]},{"type":"orderedList","start":7,"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ICE check for P2P connection"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NAT-traversal-ICE-check-for-P2P-connection"}]},{"type":"orderedList","start":8,"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If P2P unsuccessfull, make relay connection"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"NAT-traversal-P2P-unsuccessful"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/nat-traversal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/nat-traversal"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/NAT-Traversal","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"네트워크 주소 변환 탐색 투과 기술"}],"kind":"article","metadata":{"modules":[{"name":"PTT"}],"role":"collectionGroup","title":"NAT 투과 기술 (NAT Traversal)"},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT"]]},"topicSections":[{"title":"Session Traversal Utilities for NAT (STUN)","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/RFC-5389"]},{"title":"Traversal Using Relays around NAT (TURN)","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/RFC-5766"]},{"title":"Interactive Connectivity Establishment (ICE)","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/RFC-5245"]}],"references":{"NAT-traversal-STUN-binding":{"alt":null,"type":"image","identifier":"NAT-traversal-STUN-binding","variants":[{"url":"\/images\/NAT-traversal-STUN-binding.png","traits":["1x","light"]}]},"doc://com.ahnlab.lab.PTT/documentation/PTT/RFC-5245":{"role":"article","title":"RFC-5245","abstract":[{"type":"text","text":"Interactive Connectivity Establishment (ICE) 프로토콜은 기기가 공인 IP 주소로 다른 기기에 연결 하고 최적의 경로로 통신 할 수 있도록 한다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/RFC-5245","kind":"article","type":"topic","url":"\/documentation\/ptt\/rfc-5245"},"NAT-traversal-Callee-TURN-allocation":{"alt":null,"type":"image","identifier":"NAT-traversal-Callee-TURN-allocation","variants":[{"url":"\/images\/NAT-traversal-Callee-TURN-allocation.png","traits":["1x","light"]}]},"NAT-traversal-P2P-unsuccessful":{"alt":null,"type":"image","identifier":"NAT-traversal-P2P-unsuccessful","variants":[{"url":"\/images\/NAT-traversal-P2P-unsuccessful.png","traits":["1x","light"]}]},"NAT-device-to-server-make-a-video-call":{"alt":"Public-Private","type":"image","identifier":"NAT-device-to-server-make-a-video-call","variants":[{"url":"\/images\/NAT-device-to-server-make-a-video-call.png","traits":["1x","light"]}]},"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"NAT-traversal-Caller-TURN-allocation":{"alt":null,"type":"image","identifier":"NAT-traversal-Caller-TURN-allocation","variants":[{"url":"\/images\/NAT-traversal-Caller-TURN-allocation.png","traits":["1x","light"]}]},"NAT-traversal-callee-answers-OK":{"alt":null,"type":"image","identifier":"NAT-traversal-callee-answers-OK","variants":[{"url":"\/images\/NAT-traversal-callee-answers-OK.png","traits":["1x","light"]}]},"NAT-traversal-exchange-candidate-IP-addresses":{"alt":null,"type":"image","identifier":"NAT-traversal-exchange-candidate-IP-addresses","variants":[{"url":"\/images\/NAT-traversal-exchange-candidate-IP-addresses.png","traits":["1x","light"]}]},"NAT-device-to-server-view-a-web-page":{"alt":"Device-Server","type":"image","identifier":"NAT-device-to-server-view-a-web-page","variants":[{"url":"\/images\/NAT-device-to-server-view-a-web-page.png","traits":["1x","light"]}]},"doc://com.ahnlab.lab.PTT/documentation/PTT/RFC-5389":{"role":"article","title":"RFC-5389","abstract":[{"type":"text","text":"Session Traversal Utilities for NAT (STUN) 프로토콜은 기기의 공인 IP 주소를 찾아낼 수 있도록 하는 것으로, 호출자와 피호출자 간의 직접 연결을 위해 양단의 공인 IP 주소를 찾아 연결 하고자 하는 경우 사용 된다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/RFC-5389","kind":"article","type":"topic","url":"\/documentation\/ptt\/rfc-5389"},"doc://com.ahnlab.lab.PTT/documentation/PTT/RFC-5766":{"role":"article","title":"RFC-5766","abstract":[{"type":"text","text":"Traversal Using Relays around NAT (TURN) 프로토콜은 기기간의 데이터 팻킷을 전달하는 서버의 역활을 하는 것으로, 호출자와 피호출자간의 공인 IP 주소를 찾을 수 없는 경우, TURN는 두 양단간 콜을 전달해 줄수 있는 대제 기술을 제공 한다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/RFC-5766","kind":"article","type":"topic","url":"\/documentation\/ptt\/rfc-5766"},"NAT-traversal-caller-sends-invite":{"alt":null,"type":"image","identifier":"NAT-traversal-caller-sends-invite","variants":[{"url":"\/images\/NAT-traversal-caller-sends-invite.png","traits":["1x","light"]}]},"NAT-traversal-ICE-check-for-P2P-connection":{"alt":null,"type":"image","identifier":"NAT-traversal-ICE-check-for-P2P-connection","variants":[{"url":"\/images\/NAT-traversal-ICE-check-for-P2P-connection.png","traits":["1x","light"]}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Session Traversal Utilities for NAT (STUN)","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/RFC-5389"]},{"title":"Traversal Using Relays around NAT (TURN)","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/RFC-5766"]},{"title":"Interactive Connectivity Establishment (ICE)","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/RFC-5245"]}]},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}