{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelrestorationdelegate"}]},{"anchor":"Declaration","level":2,"type":"heading","text":"Declaration"},{"type":"codeListing","syntax":"objc","code":["@protocol PTChannelRestorationDelegate"]},{"type":"codeListing","syntax":"swift","code":["protocol PTChannelRestorationDelegate"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/ptchannelrestorationdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/ptchannelrestorationdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelRestorationDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"채널 복원 동작을 나타내는 유형"}],"kind":"article","metadata":{"modules":[{"name":"PTT"}],"role":"collectionGroup","title":"PTChannelRestorationDelegate"},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT"]]},"topicSections":[{"title":"채널 설명자 가져오기","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelRestorationDelegate-channelDescriptorForRestoredChannelUUID-"]}],"references":{"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"https://developer.apple.com/documentation/pushtotalk/ptchannelrestorationdelegate":{"title":"PTChannelRestorationDelegate","titleInlineContent":[{"type":"text","text":"PTChannelRestorationDelegate"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelrestorationdelegate","url":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelrestorationdelegate"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelRestorationDelegate-channelDescriptorForRestoredChannelUUID-":{"role":"article","title":"channelDescriptorForRestoredChannelUUID:","abstract":[{"type":"text","text":"관찰자에게 시스템이 채널을 복원 했음을 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelRestorationDelegate-channelDescriptorForRestoredChannelUUID-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelrestorationdelegate-channeldescriptorforrestoredchanneluuid-"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"채널 설명자 가져오기","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelRestorationDelegate-channelDescriptorForRestoredChannelUUID-"]}]},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}