{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"필수"}]}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanagerdelegate\/4002150-channelmanager"}]},{"anchor":"Declaration","level":2,"type":"heading","text":"Declaration"},{"type":"codeListing","syntax":"objc","code":["func channelManager(","    _ channelManager: PTChannelManager,","    didLeaveChannel channelUUID: UUID,","    reason: PTChannelLeaveReason",")"]},{"type":"codeListing","syntax":"swift","code":["- (void)channelManager:(PTChannelManager *)channelManager ","didLeaveChannelWithUUID:(NSUUID *)channelUUID ","                reason:(PTChannelLeaveReason)reason;"]},{"anchor":"Parameters","level":2,"type":"heading","text":"Parameters"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"channelManager"}]},{"type":"codeListing","syntax":null,"code":["채널 관리자"]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"channelUUID"}]},{"type":"codeListing","syntax":null,"code":["채널 식별자"]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"reason"}]},{"type":"codeListing","syntax":null,"code":["이탈 사유"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-didleavechannelwithuuid-reason-"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-didleavechannelwithuuid-reason-"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-didLeaveChannelWithUUID-reason-","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"앱이 Push to Talk 채널에서 이탈했음을 관찰자에게 알린다."}],"kind":"article","metadata":{"roleHeading":"Article","title":"channelManager:didLeaveChannelWithUUID:reason:","role":"article","modules":[{"name":"PTT"}]},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate"]]},"seeAlsoSections":[{"title":"채널 참여과 이탈","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-didJoinChannelWithUUID-reason-","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToJoinChannelWithUUID-error-","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToLeaveChannelWithUUID-error-"],"generated":true}],"references":{"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-didJoinChannelWithUUID-reason-":{"role":"article","title":"channelManager:didJoinChannelWithUUID:reason:","abstract":[{"type":"text","text":"앱이 Push to Talk 채널에 성공적으로 참가했음을 관찰자에게 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-didJoinChannelWithUUID-reason-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-didjoinchannelwithuuid-reason-"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-failedToLeaveChannelWithUUID-error-":{"role":"article","title":"channelManager:failedToLeaveChannelWithUUID:error:","abstract":[{"type":"text","text":"Push to Talk 채널에서 이탈하는데 실패 했음을 관찰자에게 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToLeaveChannelWithUUID-error-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-failedtoleavechannelwithuuid-error-"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate":{"role":"collectionGroup","title":"PTChannelManagerDelegate","abstract":[{"type":"text","text":"채널 관리자 라이프 사이클을 나타내는 유형"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate"},"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"https://developer.apple.com/documentation/pushtotalk/ptchannelmanagerdelegate/4002150-channelmanager":{"title":"channelManager:didLeaveChannelWithUUID:reason:","titleInlineContent":[{"type":"text","text":"channelManager:didLeaveChannelWithUUID:reason:"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanagerdelegate\/4002150-channelmanager","url":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanagerdelegate\/4002150-channelmanager"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-failedToJoinChannelWithUUID-error-":{"role":"article","title":"channelManager:failedToJoinChannelWithUUID:error:","abstract":[{"type":"text","text":"Push to Talk 채널에 참여하는데 실패 했음을 관찰자에게 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToJoinChannelWithUUID-error-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-failedtojoinchannelwithuuid-error-"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"채널 참여과 이탈","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-didJoinChannelWithUUID-reason-","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToJoinChannelWithUUID-error-","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToLeaveChannelWithUUID-error-"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}