{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"필수"}]}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanagerdelegate\/4002144-channelmanager"}]},{"anchor":"Declaration","level":2,"type":"heading","text":"Declaration"},{"type":"codeListing","syntax":"objc","code":["- (void)channelManager:(PTChannelManager *)channelManager ","           channelUUID:(NSUUID *)channelUUID ","didBeginTransmittingFromSource:(PTChannelTransmitRequestSource)source;"]},{"type":"codeListing","syntax":"swift","code":["func channelManager(","    _ channelManager: PTChannelManager,","    channelUUID: UUID,","    didBeginTransmittingFrom source: PTChannelTransmitRequestSource",")"]},{"anchor":"Parameters","level":2,"type":"heading","text":"Parameters"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"channelManager"}]},{"type":"codeListing","syntax":null,"code":["채널 관리자"]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"channelUUID"}]},{"type":"codeListing","syntax":null,"code":["채널 구분자"]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"source"}]},{"type":"codeListing","syntax":null,"code":["전송 요청 소스"]},{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"시스템은 사용자가 사용자 인터페이스에서 말하기 버튼을 누르기 시작하거나 프로그램적으로 전송이 시작할때, 혹은 핸즈-프리 액세서리 버튼을 눌러 전송이 시작될 때 이 메서드가 호출 된다."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"앱은 사용자의 오디오 녹음을 시작하기 전에 시스템이 "},{"overridingTitleInlineContent":[{"type":"text","text":"channelManager:didActivateAudioSession:"}],"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanagerdelegate\/4002144-channelmanager","overridingTitle":"channelManager:didActivateAudioSession:"},{"type":"text","text":"을 호출할 때까지 기다려야 한다."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-channeluuid-didbegintransmittingfromsource-"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-channeluuid-didbegintransmittingfromsource-"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-channelUUID-didBeginTransmittingFromSource-","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"전송이 시작됨을 관찰자에게 알린다."}],"kind":"article","metadata":{"roleHeading":"Article","title":"channelManager:channelUUID:didBeginTransmittingFromSource:","role":"article","modules":[{"name":"PTT"}]},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate"]]},"seeAlsoSections":[{"title":"전송 시작과 종료","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-channelUUID-didEndTransmittingFromSource-","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToBeginTransmittingInChannelWithUUID-error-","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToStopTransmittingInChannelWithUUID-error-"],"generated":true}],"references":{"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-channelUUID-didEndTransmittingFromSource-":{"role":"article","title":"channelManager:channelUUID:didEndTransmittingFromSource:","abstract":[{"type":"text","text":"관찰자에게 전송이 종료되었음을 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-channelUUID-didEndTransmittingFromSource-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-channeluuid-didendtransmittingfromsource-"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-failedToStopTransmittingInChannelWithUUID-error-":{"role":"article","title":"channelManager:failedToStopTransmittingInChannelWithUUID:error:","abstract":[{"type":"text","text":"관찰자에게 전송 종료에 실패 했음을 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToStopTransmittingInChannelWithUUID-error-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-failedtostoptransmittinginchannelwithuuid-error-"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-failedToBeginTransmittingInChannelWithUUID-error-":{"role":"article","title":"channelManager:failedToBeginTransmittingInChannelWithUUID:error:","abstract":[{"type":"text","text":"관찰자에게 전송 시작에 실패 했음을 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToBeginTransmittingInChannelWithUUID-error-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-failedtobegintransmittinginchannelwithuuid-error-"},"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate":{"role":"collectionGroup","title":"PTChannelManagerDelegate","abstract":[{"type":"text","text":"채널 관리자 라이프 사이클을 나타내는 유형"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate"},"https://developer.apple.com/documentation/pushtotalk/ptchannelmanagerdelegate/4002144-channelmanager":{"title":"channelManager:channelUUID:didBeginTransmittingFromSource:","titleInlineContent":[{"type":"text","text":"channelManager:channelUUID:didBeginTransmittingFromSource:"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanagerdelegate\/4002144-channelmanager","url":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanagerdelegate\/4002144-channelmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"전송 시작과 종료","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-channelUUID-didEndTransmittingFromSource-","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToBeginTransmittingInChannelWithUUID-error-","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToStopTransmittingInChannelWithUUID-error-"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}