{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"필수"}]}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanagerdelegate\/4002147-channelmanager"}]},{"anchor":"Declaration","level":2,"type":"heading","text":"Declaration"},{"type":"codeListing","syntax":"objc","code":["- (void)channelManager:(PTChannelManager *)channelManager ","didActivateAudioSession:(AVAudioSession *)audioSession;"]},{"type":"codeListing","syntax":"swift","code":["func channelManager(","    _ channelManager: PTChannelManager,","    didActivate audioSession: AVAudioSession",")"]},{"anchor":"Parameters","level":2,"type":"heading","text":"Parameters"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"channelManager"}]},{"type":"codeListing","syntax":null,"code":["채널 관리자"]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"audioSession"}]},{"type":"codeListing","syntax":null,"code":["활성화된 오디오 세션"]},{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"오디오를 녹음하고 전송하게 전에 프레임워크가 이 메소드를 호출할 때까지 기다린다. 프레임워크는 오디오 세션이 활성화되고 올바른 우선순위로 설정될 때 메소드를 호출하고 앱이 백그라운드에 있는 경우에도 오디오 녹음을 허용한다."},{"type":"text","text":" "},{"type":"text","text":"프레임워크는 채널 전송 모드가 "},{"type":"codeVoice","code":"PTTransmissionModeFullDuplex"},{"type":"text","text":"이고 전송이 시작될 때 원격 참가자로부터 오디오를 수신하기 때문에 이미 활성 오디오 세션이 있는 경우 메소드를 호출 하진 않는다."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-didactivateaudiosession-"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-didactivateaudiosession-"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-didActivateAudioSession-","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"관찰자에게 활성화된 오디오 세션을 알린다."}],"kind":"article","metadata":{"roleHeading":"Article","title":"channelManager:didActivateAudioSession:","role":"article","modules":[{"name":"PTT"}]},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate"]]},"seeAlsoSections":[{"title":"오디오 세션 활성화와 비활성화","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-didDeactivateAudioSession-"],"generated":true}],"references":{"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-didDeactivateAudioSession-":{"role":"article","title":"channelManager:didDeactivateAudioSession:","abstract":[{"type":"text","text":"관찰자에게 비활성화된 오디오 세션을 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-didDeactivateAudioSession-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-diddeactivateaudiosession-"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate":{"role":"collectionGroup","title":"PTChannelManagerDelegate","abstract":[{"type":"text","text":"채널 관리자 라이프 사이클을 나타내는 유형"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate"},"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"https://developer.apple.com/documentation/pushtotalk/ptchannelmanagerdelegate/4002147-channelmanager":{"title":"channelManager:didActivateAudioSession:","titleInlineContent":[{"type":"text","text":"channelManager:didActivateAudioSession:"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanagerdelegate\/4002147-channelmanager","url":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanagerdelegate\/4002147-channelmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"오디오 세션 활성화와 비활성화","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-didDeactivateAudioSession-"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}