{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanager\/4031739-requestbegintransmittingwithchan"}]},{"anchor":"Declaration","level":2,"type":"heading","text":"Declaration"},{"type":"codeListing","syntax":"objc","code":["- (void)requestBeginTransmittingWithChannelUUID:(NSUUID *)channelUUID;"]},{"type":"codeListing","syntax":"swift","code":["func requestBeginTransmitting(channelUUID: UUID)"]},{"anchor":"Parameters","level":2,"type":"heading","text":"Parameters"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"channelUUID"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"채설 식별자"}]},{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"앱은 포그라운드에 있거나 무선 액세서리 버튼이 "},{"type":"reference","isActive":true,"identifier":""},{"type":"text","text":" 특성 변경을 트리거하는 경우와 같이 "},{"overridingTitleInlineContent":[{"type":"text","text":"Core Bluetooth"}],"isActive":true,"type":"reference","identifier":"","overridingTitle":"Core Bluetooth"},{"type":"text","text":" 이벤트 이후에만 전송을 시작할 수 있다. 사용자는 Push to Talk 시스템 사용자 인터페이스를 사용하여 전송을 시작 할 수 도 있다."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"성공하면 "},{"type":"codeVoice","code":"PTChannelTransmitRequestSource.programmaticRequest"},{"type":"text","text":"와 함께 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-channelUUID-didBeginTransmittingFromSource-"},{"type":"text","text":"에서 콜백을 수신한다. 그렇지 않으면, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToBeginTransmittingInChannelWithUUID-error-"},{"type":"text","text":"를 통해 실패이유를 수신한다."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/ptchannelmanager-requestbegintransmittingwithchanneluuid-"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/ptchannelmanager-requestbegintransmittingwithchanneluuid-"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager-requestBeginTransmittingWithChannelUUID-","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"지정한 채널 식별자로 오디오 전송을 시작한다."}],"kind":"article","metadata":{"roleHeading":"Article","title":"requestBeginTransmittingWithChannelUUID:","role":"article","modules":[{"name":"PTT"}]},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager"]]},"seeAlsoSections":[{"title":"전송 시작과 종료","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager-stopTransmittingWithChannelUUID-"],"generated":true}],"references":{"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"https://developer.apple.com/documentation/pushtotalk/ptchannelmanager/4031739-requestbegintransmittingwithchan":{"title":"requestBeginTransmittingWithChannelUUID:","titleInlineContent":[{"type":"text","text":"requestBeginTransmittingWithChannelUUID:"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanager\/4031739-requestbegintransmittingwithchan","url":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanager\/4031739-requestbegintransmittingwithchan"},"":{"title":"Core Bluetooth","titleInlineContent":[{"type":"text","text":"Core Bluetooth"}],"type":"link","identifier":"","url":""},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManager":{"role":"collectionGroup","title":"PTChannelManager","abstract":[{"type":"text","text":"PTT 채널 관리자를 나타내는 개체이다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanager"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-channelUUID-didBeginTransmittingFromSource-":{"role":"article","title":"channelManager:channelUUID:didBeginTransmittingFromSource:","abstract":[{"type":"text","text":"전송이 시작됨을 관찰자에게 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-channelUUID-didBeginTransmittingFromSource-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-channeluuid-didbegintransmittingfromsource-"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManager-stopTransmittingWithChannelUUID-":{"role":"article","title":"stopTransmittingWithChannelUUID:","abstract":[{"type":"text","text":"지정한 채널 식별자로 오디오 전송을 중지한다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager-stopTransmittingWithChannelUUID-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanager-stoptransmittingwithchanneluuid-"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-failedToBeginTransmittingInChannelWithUUID-error-":{"role":"article","title":"channelManager:failedToBeginTransmittingInChannelWithUUID:error:","abstract":[{"type":"text","text":"관찰자에게 전송 시작에 실패 했음을 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToBeginTransmittingInChannelWithUUID-error-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-failedtobegintransmittinginchannelwithuuid-error-"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"전송 시작과 종료","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager-stopTransmittingWithChannelUUID-"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}