{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanager\/4031741-stoptransmittingwithchanneluuid"}]},{"anchor":"Declaration","level":2,"type":"heading","text":"Declaration"},{"type":"codeListing","syntax":"objc","code":["- (void)stopTransmittingWithChannelUUID:(NSUUID *)channelUUID;"]},{"type":"codeListing","syntax":"swift","code":["func stopTransmitting(channelUUID: UUID)"]},{"anchor":"Parameters","level":2,"type":"heading","text":"Parameters"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"channelUUID"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"채널 식별자"}]},{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"성공 하면, "},{"type":"codeVoice","code":"PTChannelTransmitRequestSourceProgrammaticRequest"},{"type":"text","text":"와 함께 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-channelUUID-didEndTransmittingFromSource-"},{"type":"text","text":"에서 콜백을 수신한다. 그렇지 않으면, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToStopTransmittingInChannelWithUUID-error-"},{"type":"text","text":"를 통해 실패 이유를 받는다."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/ptchannelmanager-stoptransmittingwithchanneluuid-"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/ptchannelmanager-stoptransmittingwithchanneluuid-"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager-stopTransmittingWithChannelUUID-","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"지정한 채널 식별자로 오디오 전송을 중지한다."}],"kind":"article","metadata":{"roleHeading":"Article","title":"stopTransmittingWithChannelUUID:","role":"article","modules":[{"name":"PTT"}]},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager"]]},"seeAlsoSections":[{"title":"전송 시작과 종료","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager-requestBeginTransmittingWithChannelUUID-"],"generated":true}],"references":{"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManager":{"role":"collectionGroup","title":"PTChannelManager","abstract":[{"type":"text","text":"PTT 채널 관리자를 나타내는 개체이다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanager"},"https://developer.apple.com/documentation/pushtotalk/ptchannelmanager/4031741-stoptransmittingwithchanneluuid":{"title":"stopTransmittingWithChannelUUID:","titleInlineContent":[{"type":"text","text":"stopTransmittingWithChannelUUID:"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanager\/4031741-stoptransmittingwithchanneluuid","url":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchannelmanager\/4031741-stoptransmittingwithchanneluuid"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-channelUUID-didEndTransmittingFromSource-":{"role":"article","title":"channelManager:channelUUID:didEndTransmittingFromSource:","abstract":[{"type":"text","text":"관찰자에게 전송이 종료되었음을 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-channelUUID-didEndTransmittingFromSource-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-channeluuid-didendtransmittingfromsource-"},"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManagerDelegate-channelManager-failedToStopTransmittingInChannelWithUUID-error-":{"role":"article","title":"channelManager:failedToStopTransmittingInChannelWithUUID:error:","abstract":[{"type":"text","text":"관찰자에게 전송 종료에 실패 했음을 알린다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManagerDelegate-channelManager-failedToStopTransmittingInChannelWithUUID-error-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanagerdelegate-channelmanager-failedtostoptransmittinginchannelwithuuid-error-"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManager-requestBeginTransmittingWithChannelUUID-":{"role":"article","title":"requestBeginTransmittingWithChannelUUID:","abstract":[{"type":"text","text":"지정한 채널 식별자로 오디오 전송을 시작한다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager-requestBeginTransmittingWithChannelUUID-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanager-requestbegintransmittingwithchanneluuid-"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"전송 시작과 종료","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager-requestBeginTransmittingWithChannelUUID-"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}