{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchanneldescriptor\/4002120-name"}]},{"anchor":"Declaration","level":2,"type":"heading","text":"Declaration"},{"type":"codeListing","syntax":"objc","code":["@property(nonatomic, copy, readonly) NSString *name;"]},{"type":"codeListing","syntax":"swift","code":["var name: String { get }"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/ptchanneldescriptor-name"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/ptchanneldescriptor-name"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-name","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"시스템이 시스템 사용자 인터페이스에 표시하는 채널이름이다."}],"kind":"article","metadata":{"roleHeading":"Article","title":"name","role":"article","modules":[{"name":"PTT"}]},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor"]]},"seeAlsoSections":[{"title":"참가자 검사","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-image"],"generated":true}],"references":{"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelDescriptor-image":{"role":"article","title":"image","abstract":[{"type":"text","text":"채널을 나타내기 위해 시스템이 사용자 인터페이스에 표시하는 채널 사진이다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-image","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchanneldescriptor-image"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelDescriptor":{"role":"collectionGroup","title":"PTChannelDescriptor","abstract":[{"type":"text","text":"참가자를 나타내는 개체"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchanneldescriptor"},"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"https://developer.apple.com/documentation/pushtotalk/ptchanneldescriptor/4002120-name":{"title":"name","titleInlineContent":[{"type":"text","text":"name"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchanneldescriptor\/4002120-name","url":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchanneldescriptor\/4002120-name"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"참가자 검사","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-image"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}