{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchanneldescriptor"}]},{"anchor":"Declaration","level":2,"type":"heading","text":"Declaration"},{"type":"codeListing","syntax":"objc","code":["@interface PTChannelDescriptor : NSObject"]},{"type":"codeListing","syntax":"swift","code":["class PTChannelDescriptor : NSObject"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/ptchanneldescriptor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/ptchanneldescriptor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"참가자를 나타내는 개체"}],"kind":"article","metadata":{"modules":[{"name":"PTT"}],"role":"collectionGroup","title":"PTChannelDescriptor"},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT"]]},"topicSections":[{"title":"참가자 만들기","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-initWithName-image-"]},{"title":"참가자 검사","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-image","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-name"]}],"references":{"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelDescriptor-name":{"role":"article","title":"name","abstract":[{"type":"text","text":"시스템이 시스템 사용자 인터페이스에 표시하는 채널이름이다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-name","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchanneldescriptor-name"},"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelDescriptor-image":{"role":"article","title":"image","abstract":[{"type":"text","text":"채널을 나타내기 위해 시스템이 사용자 인터페이스에 표시하는 채널 사진이다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-image","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchanneldescriptor-image"},"https://developer.apple.com/documentation/pushtotalk/ptchanneldescriptor":{"title":"PTChannelDescriptor","titleInlineContent":[{"type":"text","text":"PTChannelDescriptor"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchanneldescriptor","url":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptchanneldescriptor"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelDescriptor-initWithName-image-":{"role":"article","title":"initWithName:image:","abstract":[{"type":"text","text":"지정한 이름과 이미지로 채널 설명자를 만든다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-initWithName-image-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchanneldescriptor-initwithname-image-"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"참가자 만들기","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-initWithName-image-"]},{"title":"참가자 검사","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-image","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelDescriptor-name"]}]},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}