{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptparticipant"}]},{"anchor":"Declaration","level":2,"type":"heading","text":"Declaration"},{"type":"codeListing","syntax":"objc","code":["@interface PTParticipant : NSObject"]},{"type":"codeListing","syntax":"swift","code":["class PTParticipant : NSObject"]},{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"PTParticipant"},{"type":"text","text":" 객제를 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager-setActiveRemoteParticipant-forChannelUUID-completionHandler-"},{"type":"text","text":"와 함게 사용하여 시스템이 사용자 인터페이스를 표시하는 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-name"},{"type":"text","text":"과 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-image"},{"type":"text","text":"을 갱신한다."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/ptparticipant"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/ptparticipant"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"참가자를 나타내는 개체"}],"kind":"article","metadata":{"modules":[{"name":"PTT"}],"role":"collectionGroup","title":"PTParticipant"},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT"]]},"topicSections":[{"title":"참가자 만들기","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-initWithName-image-"]},{"title":"참가자 검사","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-name","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-image"]}],"references":{"https://developer.apple.com/documentation/pushtotalk/ptparticipant":{"title":"PTParticipant","titleInlineContent":[{"type":"text","text":"PTParticipant"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptparticipant","url":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptparticipant"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTParticipant-initWithName-image-":{"role":"article","title":"initWithName:image:","abstract":[{"type":"text","text":"지정한 이름과 이미지로 참가자를 생성한다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-initWithName-image-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptparticipant-initwithname-image-"},"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTChannelManager-setActiveRemoteParticipant-forChannelUUID-completionHandler-":{"role":"article","title":"setActiveRemoteParticipant:forChannelUUID:completionHandler:","abstract":[{"type":"text","text":"채널 식별자를 사용하여 활성 원격 참자자를 설정한다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTChannelManager-setActiveRemoteParticipant-forChannelUUID-completionHandler-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptchannelmanager-setactiveremoteparticipant-forchanneluuid-completionhandler-"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTParticipant-name":{"role":"article","title":"name","abstract":[{"type":"text","text":"참가자 이름"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-name","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptparticipant-name"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTParticipant-image":{"role":"article","title":"image","abstract":[{"type":"text","text":"참가자에 연결하는 이미지 개체"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-image","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptparticipant-image"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"참가자 만들기","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-initWithName-image-"]},{"title":"참가자 검사","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-name","doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTParticipant-image"]}]},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}