{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptpushresult"}]},{"anchor":"Declaration","level":2,"type":"heading","text":"Declaration"},{"type":"codeListing","syntax":"objc","code":["@interface PTPushResult : NSObject"]},{"type":"codeListing","syntax":"swift","code":["class PTPushResult : NSObject"]},{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"앱이 애플 푸시 알림 서비스 페이로드를 수신하면 대리자 메서드의 일부로 "},{"type":"codeVoice","code":"PTPushResult"},{"type":"text","text":" 개체를 반환한다. 시스템 사용자 인터페이스에서 최신 참가자 정보를 표시하려면 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTPushResult-pushResultForActiveRemoteParticipant-"},{"type":"text","text":"를 사용한다. 채널에서 사용자를 제거하기 위해 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTPushResult-leaveChannelPushResult"},{"type":"text","text":"를 사용한다."}]},{"type":"codeListing","syntax":"swift","code":["func incomingPushResult(channelManager: PTChannelManager,","                        channelUUID: UUID,","                        pushPayload: [String: Any]) -> PTPushResult {","    guard let activeSpeaker = pushPayload[\"activeSpeaker\"] as? String else {","        \/\/ 활성 발언자가 없다고 보고하고 채널을 나간다.","        return .leaveChannel","    }","","    let activeSpeakerImage = \/\/ 현재 발언자의 캐시된 이미지를 가져온다.","    let participant = PTParticipant(name: activeSpeaker,","                                    image: activeSpeakerImage)","    \/\/ 활성 참가자 정보를 시스템에 보고한다.","    return .activeRemoteParticipant(participant)","}",""]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ptt\/ptpushresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ptt\/ptpushresult"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTPushResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"푸시 결과를 나타내는 객체"}],"kind":"article","metadata":{"modules":[{"name":"PTT"}],"role":"collectionGroup","title":"PTPushResult"},"hierarchy":{"paths":[["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT"]]},"topicSections":[{"title":"활성 참가자 갱신","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTPushResult-pushResultForActiveRemoteParticipant-"]},{"title":"채널 이탈","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTPushResult-leaveChannelPushResult"]}],"references":{"doc://com.ahnlab.lab.PTT/documentation/PTT":{"role":"collection","title":"PTT","abstract":[{"type":"text","text":"Push To Talk (PTT) APIs"}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT","kind":"symbol","type":"topic","url":"\/documentation\/ptt"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTPushResult-leaveChannelPushResult":{"role":"article","title":"leaveChannelPushResult","abstract":[{"type":"text","text":"채널 이탈에 대한 푸시 결과를 생성한다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTPushResult-leaveChannelPushResult","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptpushresult-leavechannelpushresult"},"doc://com.ahnlab.lab.PTT/documentation/PTT/PTPushResult-pushResultForActiveRemoteParticipant-":{"role":"article","title":"pushResultForActiveRemoteParticipant:","abstract":[{"type":"text","text":"원격 참가자가 말하기 시작했음을 보고하기 위한 푸시 결과를 생성한다."}],"identifier":"doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTPushResult-pushResultForActiveRemoteParticipant-","kind":"article","type":"topic","url":"\/documentation\/ptt\/ptpushresult-pushresultforactiveremoteparticipant-"},"https://developer.apple.com/documentation/pushtotalk/ptpushresult":{"title":"PTPushResult","titleInlineContent":[{"type":"text","text":"PTPushResult"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptpushresult","url":"https:\/\/developer.apple.com\/documentation\/pushtotalk\/ptpushresult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"활성 참가자 갱신","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTPushResult-pushResultForActiveRemoteParticipant-"]},{"title":"채널 이탈","identifiers":["doc:\/\/com.ahnlab.lab.PTT\/documentation\/PTT\/PTPushResult-leaveChannelPushResult"]}]},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}